disabled = false
locale = "en"
label = "English"
weight = 1
title = "DogWYZone"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[params.author]
name = "DogWY"
email = "wangyan04221@outlook.com"
image = "logo.jpg"
headline = "狗里狗气狗东西"

[[params.author.links]]
email = "wangyan04221@outlook.com"

[[params.author.links]]
github = "https://github.com/DogWY"

[[params.author.links]]
steam = "https://steamcommunity.com/profiles/76561198851976661/"
